[package]
name = "tictactoe"
version = "0.1.0"
authors = ["Matt Law"]
readme = "README.rst"
description = "Tic-Tac-Toe written in Rust."

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
